name: Merge check
on: [push, pull_request]
jobs:
  build:
    name: Merge check
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build
      run: |
        cd protocol/grpc
        go build -v ./...
    - name: UT
      run: |
        cd protocol/grpc
        go test $(go list ./... |  grep -v third_party | grep -v examples)
    - name: UT
      run: |
        cd protocol/gin4r
        go test $(go list ./... |  grep -v third_party | grep -v examples)